using System.Collections;
using UnityEngine;
using UnityEngine.SceneManagement;

/// <summary>
/// The game's music, owned in one place and surviving scene loads (C5).
///
/// <para><b>Why not an AudioSource per scene, which is how the 2D build did it?</b> Two
/// reasons, and the second is the one that matters. Three of the six scenes
/// (<c>Level1_BarrenFarm</c>, <c>Level2_FactoryMaze</c>, <c>Shop_RecyclingStation</c>) are
/// generated by their builders, so a source placed in them survives exactly until the next
/// <i>Rebuild</i> — which is why they had no music at all. And a per-scene source restarts the
/// track from bar one on every load: in the 2D game that happened a handful of times, but this
/// build has portals running hub ↔ L1 ↔ L2 plus "Chơi lại" reloading on death, so the same
/// thirty-second loop would be forever starting over. Here the scene change is inaudible —
/// the track keeps playing across the load, and only actually changing the <i>track</i> makes
/// a sound.</para>
///
/// <para>It builds itself from <see cref="RuntimeInitializeOnLoadMethodAttribute"/>, like
/// <see cref="GameFeel"/>'s runner and <see cref="Sfx"/>'s voices, so it works no matter which
/// scene the editor started in — the levels are entered directly all the time during
/// development, and music that only exists if you came from the main menu is music that is
/// never heard while the level is being built.</para>
/// </summary>
[DisallowMultipleComponent]
public class MusicPlayer : MonoBehaviour
{
    /// <summary>Where <see cref="MusicKit"/> lives, relative to a Resources folder.</summary>
    public const string KitResourcePath = "MusicKit";

    public static MusicPlayer Instance { get; private set; }

    MusicKit kit;
    AudioSource source;
    AudioClip current;
    Coroutine fade;
    float fadeLevel = 1f;

    /// <summary>The clip playing right now, for tests and for the audio pass to verify against.</summary>
    public AudioClip CurrentTrack => current;

    // AfterSceneLoad rather than BeforeSceneLoad: the kit comes out of Resources, and the first
    // scene has to exist before there is a scene name to look its track up by.
    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
    static void Bootstrap()
    {
        if (Instance != null) return;
        var host = new GameObject("~Music");
        DontDestroyOnLoad(host);
        host.AddComponent<MusicPlayer>();
    }

    // Instance survives Fast Enter Play Mode as a destroyed object, which Unity's == null
    // already reports as null — but the reset is spelled out anyway, because "the fake null
    // happens to save us" is a thing that stops being true the moment someone stores a plain
    // C# field beside it. See the statics rule in CLAUDE.md.
    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]
    static void ResetStatics() => Instance = null;

    void Awake()
    {
        if (Instance != null && Instance != this) { Destroy(gameObject); return; }
        Instance = this;

        kit = Resources.Load<MusicKit>(KitResourcePath);
        if (kit == null)
        {
            Debug.LogWarning($"[Eco-Dash] No MusicKit at Resources/{KitResourcePath} — " +
                             "run Eco-Dash → Run the audio pass (C5). The game will be silent.");
            return;
        }

        source = gameObject.AddComponent<AudioSource>();
        source.playOnAwake = false;
        source.loop = true;
        source.spatialBlend = 0f;   // music is not in the world
        source.volume = 0f;

        GameSettings.OnChanged += ApplyVolume;
        SceneManager.sceneLoaded += OnSceneLoaded;
        Switch(SceneManager.GetActiveScene().name, instant: true);
    }

    void OnDestroy()
    {
        if (Instance == this) Instance = null;
        GameSettings.OnChanged -= ApplyVolume;
        SceneManager.sceneLoaded -= OnSceneLoaded;
    }

    void OnSceneLoaded(Scene scene, LoadSceneMode mode)
    {
        if (mode == LoadSceneMode.Additive) return;
        Switch(scene.name, instant: false);
    }

    /// <summary>Play whatever <paramref name="sceneName"/> asks for, doing nothing if it's already on.</summary>
    public void Switch(string sceneName, bool instant)
    {
        if (kit == null || source == null) return;
        var wanted = kit.For(sceneName);

        // The load that changes nothing is the common case and has to be genuinely silent —
        // not a restart, not a re-fade. Everything else here is the rare path.
        if (wanted == current && (wanted == null || source.isPlaying)) return;

        if (fade != null) { StopCoroutine(fade); fade = null; }
        if (instant || kit.fadeSeconds <= 0f)
        {
            StartTrack(wanted);
            fadeLevel = 1f;
            ApplyVolume();
        }
        else
        {
            fade = StartCoroutine(Crossfade(wanted));
        }
    }

    IEnumerator Crossfade(AudioClip wanted)
    {
        float half = kit.fadeSeconds * 0.5f;

        if (source.isPlaying)
            yield return Ramp(1f, 0f, half);

        StartTrack(wanted);
        if (wanted == null) { fade = null; yield break; }

        yield return Ramp(0f, 1f, half);
        fade = null;
    }

    // Unscaled: a track change can land on a paused frame (dying opens the lose panel and
    // pins Time.timeScale at 0), and a fade driven by scaled time would stop halfway down.
    IEnumerator Ramp(float from, float to, float seconds)
    {
        float t = 0f;
        while (t < seconds)
        {
            t += Time.unscaledDeltaTime;
            fadeLevel = Mathf.Lerp(from, to, seconds <= 0f ? 1f : t / seconds);
            ApplyVolume();
            yield return null;
        }
        fadeLevel = to;
        ApplyVolume();
    }

    void StartTrack(AudioClip clip)
    {
        current = clip;
        source.Stop();
        source.clip = clip;
        if (clip != null) source.Play();
    }

    void ApplyVolume()
    {
        if (source == null || kit == null) return;
        source.volume = kit.volume * GameSettings.EffectiveMusic * fadeLevel;
    }
}
